# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: dependencies
    before: # plantuml server http://localhost:8080
      docker run -d -p 8080:8080 plantuml/plantuml-server:tomcat
    init: | # runs during prebuild
      npm install -g npm@latest
      npm install
    command: npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000 # local
    # onOpen: open-browser
    visibility: public
  - port: 8080 # plantuml server http://localhost:8080
    visibility: public

# list of vscode extensions which should be installed for users of this workspace
vscode:
  extensions:
    # Prettier
    - esbenp.prettier-vscode
    # Eslint
    - dbaeumer.vscode-eslint
    # Live Server
    - ritwickdey.liveserver
    # vscode-icons
    - vscode-icons-team.vscode-icons
    # ENV
    - IronGeek.vscode-env
    # NPM Intellisense
    - christian-kohler.npm-intellisense
    # GitLens
    - eamodio.gitlens
    # Docker
    - ms-azuretools.vscode-docker
    # Vetur
    - octref.vetur
    # Plantuml
    - jebbs.plantuml

#
github:
  prebuilds:
    # enable checks fail when the prebuild failed
    addCheck: prevent-merge-on-error
